FreelanceProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("freelancer_profile.urls", namespace="freelancer_profile")),
]

freelancer_profile/urls.py
from django.urls import path
from .views import index,search_data,get_behance_images

app_name = "freelancer_profile"
urlpatterns = [
    path("", view=index, name="home"),
    path("search/", view=search_data, name="search"),
    path("images/<int:id>/", view=get_behance_images, name="get_image"),

]

freelancer_profile/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class Freelancer(models.Model):
    name = models.CharField(_("Name"), max_length=50)
    url = models.URLField(_("URL"), max_length=200)
    phone = PhoneNumberField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

freelancer_profile/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from phonenumber_field.formfields import PhoneNumberField
from .models import Freelancer

class FreelancerForm(forms.ModelForm):
        phone = PhoneNumberField(widget=forms.TextInput(attrs={'placeholder': _('Phone')}), 

                       label=_("Phone number"), required=False)
        class Meta:
            model = Freelancer
            fields = ("name","url","phone")
    
    

freelancer_profile/views.py
import re

from django.shortcuts import render, get_object_or_404
from django.contrib import messages

# Selenium
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

# BeautifulSoup
from urllib.request import urlopen
from bs4 import BeautifulSoup


from .models import Freelancer
from .forms import FreelancerForm


# Create your views here.
def index(request):
    if request.method == 'POST':
        form = FreelancerForm(request.POST)
        if form.is_valid():
            data = form.save()
            messages.success(
                request, 'Data of  {} has been added!'.format(data.name))
    else:
        form = FreelancerForm()

    context = {
        'freelancers': Freelancer.objects.all(),
        'form': form,


    }
    return render(request, 'freelancer_profile/index.html', context=context)


def search_data(request):
    search = request.POST.get("search")
    form = FreelancerForm()
    try:
        freelancers = Freelancer.objects.filter(name__icontains=search)
    except:
        freelancers = None

    context = {
        'freelancers': freelancers,
        'form': form,
    }
    return render(request, 'freelancer_profile/search.html', context=context)


def get_behance_images(request, id):

    user = get_object_or_404(Freelancer, pk=id)
    html = urlopen(user.url)
    bs = BeautifulSoup(html, 'html.parser')
    images = bs.find_all('img', {'src': re.compile('.jpg')})
    img_urls = []
    print(images)
    for image in images:
        img_urls.append(image['src'])
        
        print(image['src']+'\n')

    context = {
        'freelancer': user,
        'all_images': img_urls,
    }
    return render(request, 'freelancer_profile/get_images.html', context=context)

templates/base.html
{% load static i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Freelancer Project{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">



  {% block css %}
  <!-- Latest compiled and minified Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  
  <!-- Your stuff: Third-party CSS libraries go here -->
  <!-- This file stores project-specific CSS -->
  <link href="{% static 'css/project.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% endblock %}
  <!-- Le javascript
    ================================================== -->
  {# Placed at the top of the document so pages load faster with defer #}
  {% block javascript %}
  <!-- Bootstrap JS and its dependencies-->
  <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
  </script>
  <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>

  <!-- Your stuff: Third-party javascript libraries go here -->



  {% endblock javascript %}

</head>

<body id="app">

  <div class="mb-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand bg-green-500" href="{% url 'freelancer_profile:home' %}">FeeLancer Project</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'freelancer_profile:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
        </ul>

        <form action="{% url "freelancer_profile:search" %}" method="post" class="form-inline">
            {% csrf_token %}
            <div class="form-group row">
                <input type="text" name="search" class="textinput textInput form-control mr-2" id="">
                <input type="submit" name="submit" value="Search" class="btn btn-primary " id="submit-id-submit" />
            </div>
            
        </form>
      </div>
    </nav>

  </div>
  <div class="container">
  
    {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button"
        class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock content %}

  </div> <!-- /container -->


  {% block inline_javascript %}
  {% endblock inline_javascript %}
</body>

</html>

templates/freelancer_profile/get_images.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}



<div class="row mt-5">
        <table class="table">
        <thead>
            <tr>
            <th scope="col">Name</th>
            <th scope="col">Phone</th>
            <th scope="col">URL</th>
            </tr>
        </thead>
        <tbody>

                <tr>
                    <td>{{freelancer.name}}</td>
                    <td>{{freelancer.phone}}</td>
                    <td>{{freelancer.url}}</td>
                </tr>

        </tbody>
        </table>
</div>
<hr>
<div>
    <h3>Portfolio</h3>
    <div class="d-flex flex-wrap ">
        <br>
        {% if all_images %}
            {% for imagelink in all_images %}
            
            <img src="{{imagelink}}" alt="" class="img-thumbnail">
            
                
            {% endfor %}
        {% else %}
            <h3>No Image Found</h3>
        {% endif %}
    </div>
</div>


{% endblock content %}

templates/freelancer_profile/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}


<div class="col">
    <H3>Add Data</H3>
    <form action="{% url 'freelancer_profile:home' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="submit" value="Submit" class="btn btn-primary " id="submit-id-submit" />
    </form>
</div>


<div class="row mt-5">
    {% if freelancers %}
        <table class="table">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Phone</th>
            <th scope="col">URL</th>
            <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>

            {% for freelancer in freelancers %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{freelancer.name}}</td>
                    <td>{{freelancer.phone}}</td>
                    <td>{{freelancer.url}}</td>
                    <td><a href="{% url 'freelancer_profile:get_image' freelancer.id %}">
                        <button class="btn btn-primary">Get Images</button>
                    </a>
                    </td>
                </tr>
            {% endfor %}

        </tbody>
        </table>
    {% else %}

        <h3>No Results Found</h3>

    {% endif %}
</div>


{% endblock content %}

templates/freelancer_profile/search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}



<div class="row mt-5">
    {% if freelancers %}
        <table class="table">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Phone</th>
            <th scope="col">URL</th>
            <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>

            {% for freelancer in freelancers %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{freelancer.name}}</td>
                    <td>{{freelancer.phone}}</td>
                    <td>{{freelancer.url}}</td>
                    <td><a href="#">
                        <button class="btn btn-primary">Get Images</button>
                    </a>
                    </td>
                </tr>
            {% endfor %}

        </tbody>
        </table>
    {% else %}

        <h3>No Search Result Found</h3>

    {% endif %}
</div>


{% endblock content %}